package main

import (
	"go-hw/task1"
)

func main() {
	task1.Start()
	// task2.Start()
	// task3.Start()
	// task3_1.Start()
	// task4.Start()
	// task5.Start()
	// task6.Start()
	// task6_1.Start()
	// task7.Start()
	// task8.Start()
	// task9.Start()
	// task10.Start()
	// task11.Start()
	// task12.Start()
	// task13.Start()
	// task14.Start()
	// task15.Start()
	// task16.Start()
	// task17.Start()
	// task18.Start()
	// task19.Start()
	// task20.Start()
	// task21.Start()
	// task22.Start()
	// task23.Start()
	// task24.Start()
	// task25.Start()
	// task26.Start()
	// task27.Start()
	// task28.Start()
	// task29.Start()
	// task30.Start()
	// task31.Start()
	// task32.Start()
	// task33.Start()
	// task34.Start()
}
